#服务器端口设置
server:
  port: 8082 #8092
#redis地址设置
spring:
  redis:
    host: 10.27.213.239
    password: PTRkygl@413
  artemis:
    port: 6379
  application:
    name: data-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/


